minimal improvements

diff --git a/.github/workflows/check-nix-format.yaml b/.github/workflows/check-nix-format.yaml
--- a/.github/workflows/check-nix-format.yaml
+++ b/.github/workflows/check-nix-format.yaml
@@ -10,16 +10,28 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+
       - uses: cachix/install-nix-action@v31
         with:
           nix_version: latest
           extra_nix_config: |
             experimental-features = nix-command flakes
-      - name: Install fd
-        run: nix profile install nixpkgs#fd
-      - name: Install nixfmt-rfc-style
-        run: nix profile install nixpkgs#nixfmt-rfc-style
-      - name: Check Nix format with nixfmt
+
+      - name: Install dependencies
+        run: |
+          nix profile install nixpkgs#fd
+          nix profile install nixpkgs#nixfmt-rfc-style
+
+      - name: Check Nix formatting
         run: |
           set -euo pipefail
-          fd --extension nix --exec nixfmt --check {}
+
+          fd . -name "*.nix" | while read file; do
+            echo "Tests $file"
+            if ! nixfmt --check "$file"; then
+              echo "❌ ERROR $file"
+              echo "::error file=$file::run nixfmt pls!!!"
+              exit 1
+            fi
+          done
+          echo "✅"
